version: "3"
services:
  jobs-db:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - jobs-data:/data/db
  web:
    build: ./Web
    volumes:
      - './Web:/usr/src/app'
      - /usr/src/app/node_modules/
    ports:
      - 80:3000
    depends_on:
      - jobs-db
volumes:
  jobs-data: