version: "3"
services:
  diff-server:
    # image: stolemyusername/diffr
    build: ./Diff
    volumes:
    - /Users/guy/src/diffr/Diff:/usr/src/app
    networks:
      - jobs
      - web
  jobs-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - jobs-data
  web-server:
    build: ./Web
    ports:
      - 80:3000
    depends_on:
      - jobs-db
networks:
  web:
  jobs:
volumes:
  jobs-data: